### PR TITLE
Allowing relative date format.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
This permits the values for date fields to be entered relative to the current date rather than absolute. This is much more helpful for testing features that have a sense of past and future.  For instance, a view that displays future events or a blog that displays only passed

**Comment by jhedstrom** [comment]
Seems to be a parsing error:

```
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in ./src/Drupal/Driver/Fields/Drupal8/DatetimeHandler.php on line 5
```

The branch could also use a rebase of the latest master.

**Comment by grasmash** [comment]
@jhedstrom Resolved and rebased!

**Comment by jhedstrom** [comment]
Needs a code comment shortened for coding standards check :)

**Comment by jhedstrom** [comment]
Awesome, thanks!

**Comment by jonathanjfshaw** [comment]
#126  now rerolled to allow for this

**Pull request merged**
