### PR TITLE
Test list boolean field with blank 'On' and 'Off' values.

### PR DESCRIPTION
**Pull request by nlisgo**
I've noticed a bug if I am trying to set the value '0' for a list boolean field when the Off value is blank in the settings.

### CODE REVIEW

**Comment by jhedstrom** [comment]
Does this have corresponding equivalents in either Drupal 6 or 8?

**Comment by nlisgo** [comment]
The ListBooleanHandler was added 15 days ago and has just been introduced for Drupal7. I support adding it for D6 and D8 but surely it shouldn't hold up this fix.

https://github.com/jhedstrom/DrupalDriver/pull/43

**Comment by nlisgo** [comment]
If it is not clear, the first failing commit is a test-only commit. I introduced a test to demonstrate the bug and the second commit fixes the bug.

**Comment by jhedstrom** [comment]
Makes sense to me, thanks!

**Comment by nlisgo** [comment]
Thanks for maintaining the project. It's been invaluable to us.

**Comment by jhedstrom** [comment]
Glad you're using it!

**Pull request merged**
