### PR TITLE
Use autoload.php in favour of core/vendor/autoload.php

### PR DESCRIPTION
**Pull request by webflo**
Core introduced the autoload.php a while ago. Changed the bootstrap in Drupal8, its follows very close what we have in [index.php](https://github.com/drupal/drupal/blob/8.0.x/index.php#L17).

### CODE REVIEW

**Comment by webflo** [comment]
The test failures are unrelated to this PR. mockery/mockery requires PHP 5.4 

@jhedstrom Should i change the mockery/mockery constraint to the last 5.3 compatible release?

**Comment by jhedstrom** [comment]
@webflo I removed php 5.3 from travis, but if you want to update the composer.json with the last 5.3-compatible version, that would be awesome!

**Comment by webflo** [comment]
Rebased onto master. I make another PR for 5.3 compatibility. Accordion to packagist is mockery 0.9.4 the last version that supports PHP 5.3.

**Comment by webflo** [comment]
https://packagist.org/packages/mockery/mockery

**Comment by jhedstrom** [comment]
Thanks!

**Pull request merged**
