### PR TITLE
Stop clearStaticCache from throwing warnings

### PR DESCRIPTION
**Pull request by sherakama**
A few contexts don't like this function and add warnings to my output.
the api_driver is set to 'drush'

```
  ╳  No ability to clear static caches in Drupal\Driver\DrushDriver. Put `@api` into your feature and add an API driver (ex: `api_driver: drupal`) in behat.yml. (Drupal\Driver\Exception\UnsupportedDriverActionException)
  │
  └─ @AfterScenario @api # Drupal\DrupalExtension\Context\DrupalContext::clearStaticCaches()
  │
  ╳  No ability to clear static caches in Drupal\Driver\DrushDriver. Put `@api` into your feature and add an API driver (ex: `api_driver: drupal`) in behat.yml. (Drupal\Driver\Exception\UnsupportedDriverActionException)
  │
  └─ @AfterScenario @api # Drupal\DrupalExtension\Context\MessageContext::clearStaticCaches()
  │
  ╳  No ability to clear static caches in Drupal\Driver\DrushDriver. Put `@api` into your feature and add an API driver (ex: `api_driver: drupal`) in behat.yml. (Drupal\Driver\Exception\UnsupportedDriverActionException)
  │
  └─ @AfterScenario @api # Drupal\DrupalExtension\Context\DrushContext::clearStaticCaches()
```

### CODE REVIEW

**Comment by jhedstrom** [comment]
Hmm, not sure why this change isn't passing phpcs in the build. The change looks valid.

**Comment by sherakama** [comment]
@jhedstrom, I seemed to have missed a curly brace in the `@inheritdoc` comment.

**Comment by jhedstrom** [comment]
Thanks!

**Comment by sherakama** [comment]
:+1: Ty.

**Pull request merged**
